### ISSUE TITLE
Enable Invisible Recaptcha

### ISSUE THREAD

**Issue by mattmeye** [VividCortex/angular-recaptcha#174] opened 2016-12-13 18:21 UTC
Invisible reCAPTCHA Integration
1. If you haven’t integrated your site with reCAPTCHA v2 , please follow our developer
guide for implementation details.
2. Please make sure that your site key that has been whitelisted for Invisible reCAPTCHA.
3. To enable the Invisible reCAPTCHA, rather than put the parameters in a div, you can
add them directly to an html button.
a. data-callback=””. This works just like the checkbox captcha, but is required for
invisible.
b. data-badge: This allows you to reposition the reCAPTCHA badge (i.e. logo and
‘protected by reCAPTCHA’ text) . Valid options as ‘bottomright’ (the default),
‘bottomleft’ or ‘inline’ which will put the badge directly above the button. If you
make the badge inline, you can control the CSS of the badge directly.
4. Verifying the user’s response has no changes.

**Comment by TheSharpieOne** [comment] 2016-12-13 19:55
Invisible reCAPTCHA doesn't appear to be open to the general public yet (site currently says "Coming soon"). You have to go through a special registration process. This makes it difficult to integrate with and test.
ref: https://www.google.com/recaptcha/intro/comingsoon/invisible.html

It would be interesting to see how this would integrate with the current code. Some concerns such as validation (ensuring the checkbox is checked) go away. Another things revolve around whether the directive will create the button or just be attached to one. Many of the other parameters are no longer available since they do not do anything with the 'invisible' recaptcha.

Not too sure if it would be best to create a new directive for this or modify the existing directive to handle both cases (since both deal with similar concerns).

**Comment by mattmeye** [comment] 2016-12-14 10:06
yes, you are right,

more documentation is now online: https://developers.google.com/recaptcha/docs/invisible

**Comment by TheSharpieOne** [comment] 2016-12-14 18:22
I was testing out the new invisible recaptcha on jsfiddle (https://jsfiddle.net/0x3c3goy/) and it has some interesting issues which could cause problems with normal use, not to mention how it would integrate into angular.
Most people use ngSubmit or attach ngClick on button with callbacks when the form is submitted. This does not work well with the new invisible recaptcha. The user would need to use the `onSuccess` callback (just callback to recaptcha) which passes the token indicates both a successful recaptcha validation and a form submission. The user would not be able to tie into their existing form submission workflow as easily, forcing them to do it the "vcRecaptcha way".

**Comment by nickdnk** [comment] 2017-01-05 15:36
I would say +1 for this also. I just spent an entire night trying to get it to work with the existing code. Needless to say, I failed.

**Comment by bionetmarco** [comment] 2017-01-20 23:33
I was able to set up Invisible Recaptcha quite easily.

Firstly, set your button as the vc-recaptcha. 

```
<button class="btn g-recaptcha"
    vc-recaptcha
    key="model.key"
    on-create="setWidgetId(widgetId)"
    on-success="setResponse(response)"
    on-expire="cbExpiration()">SIGN UP</button>
``` 

Then, ensure your `$scope.model.key` is an invisible recaptcha key, and simply call your signup function from `$scope.setResponse`, where `$scope.response` is the value to send back to your server.

```
$scope.model = {
    key: '** YOUR INVISIBLE RECAPTCHA KEY **'
};

$scope.setResponse = function (response) {
    $scope.response = response;
    $scope.signUp();
};

$scope.setWidgetId = function (widgetId) {
    $scope.widgetId = widgetId;
};

$scope.cbExpiration = function() {
    vcRecaptchaService.reload($scope.widgetId);
    $scope.response = null;
};
```

**Comment by Mr-Anonymous** [comment] 2017-02-12 20:16
I followed @bionetmarco said and he is right, its very easy to implement Invisible Recaptcha to the submit button directly. his instruction worked perfect and I am able to get this to work. So thank you @bionetmarco 

However, when using the Invisible ReCaptcha, although the form submit works, I get this error in Chrome console when the button is clicked:
```
Uncaught TypeError: Cannot read property 'style' of null
    at gi (recaptcha__en.js:123)
    at Pn.<anonymous> (recaptcha__en.js:266)
```

**Comment by blaketastic2** [comment] 2017-02-26 19:44
@Mr-Anonymous I got around this problem with adding this to my page:
`
                            <div class="g-recaptcha" data-size="invisible"></div>`

**Comment by EhsanKia** [comment] 2017-03-15 06:40
Works great, tiny problem I have, the first time you press, key is set and my signup is ran, but after that, the next time they press it again, nothing happens.

**Comment by MaximeCheramy** [comment] 2017-03-23 11:10
I can confirm that bionetmarco's solution works, however I have the same issue than EhsanKia. Therefor, if there's an error in the form, the captcha is used once but the user can't submit it again.
If I wait long enough I can submit again, sometimes after an error contacting reCaptcha server...

**Comment by MaximeCheramy** [comment] 2017-03-23 15:21
I've found a fix:

In my form:

```
<div vc-recaptcha key="model.key" on-success="registerForReal(response)" size="invisible" required="false"></div>
```

In the submit function of the form:

```
    if (form.$valid) {
      vcRecaptchaService.reload($scope.widgetId);
      vcRecaptchaService.execute($scope.widgetId);
    }
```

The execute function is provided by https://github.com/VividCortex/angular-recaptcha/pull/188

**Comment by sleepydada** [comment] 2017-03-24 03:03
@MaximeCheramy 
Are you attaching the same attributes to a button too, or are you just using the div?

**Comment by MaximeCheramy** [comment] 2017-03-24 06:50
I'm only using the div as explained in the recaptcha documentation: https://developers.google.com/recaptcha/docs/invisible#programmatic_execute
This way, I trigger the captcha only when the form is valid. The way I'm using it with angular-recaptcha is probably a bit of a hack though. But it seems to work...

**Comment by sleepydada** [comment] 2017-03-24 15:53
@MaximeCheramy 
Thanks for your reply! For me, it gave an error saying that vcRecaptchaService.execute was not a function, but it worked when I replaced it with grecaptcha.execute().

**Comment by ViieeS** [comment] 2017-04-06 15:04
Is it #188 working solution? When it will be merged?

**Comment by mr-cpp** [comment] 2017-04-06 16:15
@ViieeS 
Yes. It works. I also wonder will it be merged
But one unpleasant moment that there is no callback from library after form validation
i need to get the response with captcha's code before sending request to my server

**Comment by ViieeS** [comment] 2017-04-07 14:05
@mr-cpp I solved this based on trunk version.

#### Sequence:
`validate->execute->onCallback->send->handleHttpResponce(ok|fail)`

```html
<div
       vc-recaptcha
       required="false"
       size="invisible"
       on-create="setWidgetId(widgetId)"
       on-success="setResponse(response)"
       on-expire="cbExpiration()"></div>
```

```js
$scope.data = {
    response: null,
    widgetId: null
};

$scope.setResponse = function (response) {
    $log.debug('Response available');
    $scope.data.response = response;
    send();
};

$scope.setWidgetId = function (widgetId) {
    $log.debug('Created widget ID: %s', widgetId);
    $scope.widgetId = widgetId;
};

$scope.cbExpiration = function () {
    $log.debug('Captcha expired. Resetting response object');
    vcRecaptchaService.reload($scope.data.widgetId);
    $scope.data.response = null;
};

$scope.submit = function () {
    grecaptcha.execute($scope.data.widgetId);
};

var send = function () {
    // Http request, send $scope.data
    .then(function () {
        // onSucces...
    }).catch(function (errors) {
        // onFail...
        $scope.cbExpiration();
    });
};
```

**Comment by PLPeeters** [comment] 2017-04-11 13:34
@ViieeS @Mr-Anonymous I found a workaround for the reload issue: I don't use the `reload()` function of the `vcRecaptchaService` and use an `ngIf` instead.

Just add `ng-if="showRecaptcha"` to the `vc-recaptcha` `div`, then change the `cbExpiration()` function to:

    $scope.cbExpiration = function() {
        $scope.showRecaptcha = false;

        $timeout(function() {
            $scope.showRecaptcha = true;
        });
    }

Don't forget to initialize `$scope.showRecaptcha` to `true` at the top of your controller.

**Comment by ViieeS** [comment] 2017-04-13 12:53
@PLPeeters not bad) Where are the authors of repo?

P.S. Needs to merge #188

**Comment by spengilley** [comment] 2017-04-26 10:27
Looks like #188 has now been merged into release 4.1.0

**Comment by iambrosi** [comment] 2017-04-26 19:32
Done in #188. Closing now.

**Closed by iambrosi** 2017-04-26 19:32 UTC

**Comment by robertop87** [comment] 2017-11-27 23:35
reCaptcah does not work under proxy :'(

**Comment by nickdnk** [comment] 2017-11-27 23:45
Proxy is not in the application layer, so it probably doesn’t have anything to do with this library.

On 28 Nov 2017, at 00.35, Luis Roberto Perez Rios <notifications@github.com<mailto:notifications@github.com>> wrote:


reCaptcah does not work under proxy :'(

**Comment by sejas** [comment] 2018-04-18 12:37
You just need to call to `grecaptcha.execute()`
Maybe with a little timeout:
```
$timeout(function () {
        grecaptcha.execute()
     }, 1000)
``` 

You don't need to add a form tag in the html, just the vc-recaptcha:
```
      <div vc-recaptcha
           key="ctrl.key"
           size="invisible"
           on-create="ctrl.widgetId = widgetId"
           on-success="ctrl.onSuccess(response)">
      </div>
```
