### ISSUE TITLE
TypeError: b.render is not a function

### ISSUE THREAD

**Issue by drakanor** [VividCortex/angular-recaptcha#226] opened 2018-05-04 08:50 UTC
Since yesterday I'm getting the following error when loading the angular-recaptcha. It ran flawlessly for months. Did Google change something in their Recpatcha response? I have just updated it to the latest version, but no change:

TypeError: b.render is not a function
    at c.js:496
    at c.js:142
    at m.$digest (c.js:153)
    at m.$apply (c.js:156)
    at c.js:118 "Possibly unhandled rejection: {}"

**Comment by drakanor** [comment] 2018-05-04 09:26
We were able to solve the issue by removing

<script
    src="https://www.google.com/recaptcha/api.js?onload=vcRecaptchaApiLoaded&render=explicit"
    async defer>
</script>

from the page head. Looks like the plugin does this by itself. Why this was working for months is unclear to us.

**Comment by mtrias** [comment] 2018-05-04 10:28
Looks like a duplicate of #224 which was fixed by #225 and released in `4.1.4`.
Have you tried that version? Please reopen if still doesn't work for you.

**Closed by mtrias** 2018-05-04 10:28 UTC

**Comment by hehg24** [comment] 2018-05-04 15:34
Is anyone aware of what caused this issue to begin occurring yesterday?  I don't see any information on this outside of this project.  Thank you.

**Comment by mtrias** [comment] 2018-05-04 15:44
My bet would be a change in Google's code. Just a minor change like an early definition of the module, (like `grecaptcha = {}`) on their side would trigger this bug.

**Comment by drakanor** [comment] 2018-05-04 15:46
4.1.4 does not fix this. Already included <script> tags pointing to the Google Recaptcha API still cause this error in all our test devices. We tried with latest Chrome and Firefox.
There seems to be a timing issue involved, because when you try often enough it works in a few calls.

**Comment by hehg24** [comment] 2018-05-04 15:58
@drakanor That is the behavior i experienced, being a possible timing issue.  Tests so far suggest that removing the script call is required.

**Comment by williambueti** [comment] 2018-05-07 23:55
From [what I gathered](https://twitter.com/rauchg/status/991808919495307265) from a convo with @rauchg, it seems like calling Google for api.js loads a secondary script now (before, it just loaded api.js with the onload calling vcRecaptchaApiLoaded).

**Comment by Karthiklakram1** [comment] 2018-07-05 10:29
Change return b.render(a, e); to **setTimeout(function () { return b.render(a, e) }, 100);}**
