### ISSUE TITLE
Form validation on fallback mode

### ISSUE THREAD

**Issue by ripfire44** [VividCortex/angular-recaptcha#137] opened 2016-05-04 21:43 UTC
The form validation on recaptcha works just fine on most modern browsers. However, I noticed that when it's using the fallback option, it's returning a form validation error for recaptcha when the user copy & paste into the input.

**Comment by ripfire44** [comment] 2016-05-05 16:17
Did a little bit more debugging and I found out that with the fallback option, it's not calling the `callback` from the `POST`. I'm guessing this is by design. I'll just have to figure another way around in the meantime.

**Comment by jrauschenbusch** [comment] 2016-05-23 10:34
This ticket is a duplicate of https://github.com/VividCortex/angular-recaptcha/issues/46. By applying the discussed patch the fallback mode works fine.

**Comment by mtrias** [comment] 2017-01-18 20:15
Closing as duplicate then. Please reopen if i'm wrong.

**Closed by mtrias** 2017-01-18 20:15 UTC
