### ISSUE TITLE
vcRecaptchaService.reload() not reseting form validation

### ISSUE THREAD

**Issue by jasonfutch** [VividCortex/angular-recaptcha#120] opened 2016-03-13 11:26 UTC
Calling vcRecaptchaService.reload() does reset the reCAPTCHA but does not reset form validation.

The notes in your code says the following, but it is not the case.
// reCaptcha will call the same callback provided to the
// create function once this new captcha is resolved.

**Comment by TheSharpieOne** [comment] 2016-03-13 16:03
Duplicate of #69 fixed in #116. The changes are in master, but not yet released.

**Comment by jasonfutch** [comment] 2016-03-14 10:10
Thanks! Any ETA on getting that release into the bower version?

**Comment by jasonfutch** [comment] 2016-03-14 10:13
Never mind.. I forgot you can do the following in bower

"angular-recaptcha": "VividCortex/angular-recaptcha#master"

**Comment by jasonfutch** [comment] 2016-03-14 10:18
Well crap.. that pulls in the master branch but only the release folder and not the src so I guess I'll have to wait for actual release or branch it off in the mean time.

**Comment by mtrias** [comment] 2016-03-15 14:49
Sorry about that @jasonfutch we are going to work on this next week.

**Comment by mtrias** [comment] 2016-04-02 22:47
The release was done, so i believe nothing else neede here? Please reopen otherwise.

**Closed by mtrias** 2016-04-02 22:47 UTC
