### ISSUE TITLE
Bootstrap + AngualarJS form validation +  angular-recaptcha

### ISSUE THREAD

**Issue by Webinator2129** [VividCortex/angular-recaptcha#96] opened 2015-12-24 21:21 UTC
the Bootstrap + AngualarJS form validation +  angular-recaptcha is failing and its very unclear what is the cause, would be extremely helpful with some examples

<img width="529" alt="screen shot 2015-12-24 at 16 20 37" src="https://cloud.githubusercontent.com/assets/1534356/11997975/5b557cfa-aa5a-11e5-951b-e0dac4787c36.png">

**Comment by Webinator2129** [comment] 2015-12-24 21:46
the form validation fails somehow and does not seem to be able to ignore
<img width="586" alt="screen shot 2015-12-24 at 16 44 06 copy" src="https://cloud.githubusercontent.com/assets/1534356/11998092/d20d8e8e-aa5d-11e5-8427-3846dbe1cd8c.png">

**Comment by TheSharpieOne** [comment] 2015-12-24 22:35
You can move the recaptcha element outside of your form if you don't want the form to be marked as invalid when the recaptcha is not "checked".  Right now there is not an easy way to opt out of the form validation. Perhaps a change should be made to utilize the required attribute to opt in or something else to opt out.

**Comment by Webinator2129** [comment] 2015-12-24 23:13
it would look very awkard to have a form with this design, have not even checked what other dependencies there are...  especially with backend validation and formatting 

<img width="536" alt="screen shot 2015-12-24 at 18 12 34" src="https://cloud.githubusercontent.com/assets/1534356/11998366/00d82ad8-aa6a-11e5-9543-ceeaa43678dc.png">

**Comment by leosuncin** [comment] 2016-01-07 05:48
If recaptcha is inside your form will raise a error if it is not checked therefore your form will have error
![Imgur](http://i.imgur.com/p8QhvOO.png)
And if is checked and the rest of your form is valid, you can submit the form
![Imgur](http://i.imgur.com/2UmSiW5.png)

**Comment by TheSharpieOne** [comment] 2016-01-07 15:56
That is correct. As stated before, there is no easy way to opt out of that feature; which I believe is what @Webinator2129 is needing/wanting.

**Comment by zcoban** [comment] 2016-02-07 10:19
I see Failed validation but why i don't know.

**Comment by TheSharpieOne** [comment] 2016-02-07 17:13
Posting your code would help track it down, but it looks like you are not sending the captcha response to the server correctly and the server is returning an error.

**Comment by zcoban** [comment] 2016-02-07 18:50
When i try usage.html i see too same failed validation.you can look usage.html file.

**Comment by TheSharpieOne** [comment] 2016-02-07 18:56
So.. the part that say:
```
 /**
                     * SERVER SIDE VALIDATION
                     *
                     * You need to implement your server side validation here.
                     * Send the reCaptcha response to the server and use some of the server side APIs to validate it
                     * See https://developers.google.com/recaptcha/docs/verify
                     */
```
Working as intended.

**Comment by zcoban** [comment] 2016-02-07 19:00
Thank you i will try .

**Closed** 2016-02-08 13:09 UTC

**Comment by jack-gaojz** [comment] 2018-07-31 03:26
Actually, the form "$error.required" still there, it will block the form validate when we set "requred='false'" to the recaptcha:
`<div vc-recaptcha key="xxxx" requred="false"></div>`
![image](https://user-images.githubusercontent.com/40879710/43435684-a0a0168a-94b3-11e8-873d-12f96a54dc88.png)
Who can help me figure out how to fix it? thanks so much.
